### ISSUE TITLE
Build Failure After Upgrading to Tizen Studio 6.1

### ISSUE THREAD

**Issue by fjavierhrecinos** [Samsung/tizen-docs#2100]
After upgrading from Tizen Studio 6.0 to Tizen Studio 6.1, building a Web Application via the terminal fails with a NoClassDefFoundError related to org.eclipse.core.runtime.Plugin.
Previously, the build process worked correctly using Tizen Studio 6.0.

**Environment**
Tizen Studio Version: 6.1

Previous Tizen Studio Version: 6.0

Java Version: 11 (initially Java 8 was used; upgrading to Java 11 did not solve the issue)

OS: Windows 10,

**Steps to Reproduce**
Update Tizen Studio from 6.0 to 6.1.

Attempt to build a Web Application using the CLI.

Observe the build process fail at 80% with the following error:

![Image](https://github.com/user-attachments/assets/0db5a20e-8c91-4276-97f4-6737a013f4cf)

**Observations**
When using Tizen Studio 6.0, the build was successful without issues.

After updating to Tizen Studio 6.1, the build process fails consistently.

Initially, Java 8 was configured. After encountering the error, Java was updated to Java 11, but the error persists.

**Expected Behavior**
The application should compile successfully via the terminal, as it did under Tizen Studio 6.0.

**Actual Behavior**
The build fails at around 80% with a NoClassDefFoundError indicating a missing org.eclipse.core.runtime.Plugin class.

**Comment by theojin** [comment]
Hello, and thank you for filing this issue. We are very sorry for the long delay in responding.

This issue is related to Tizen Studio / SDK / Emulator / Package Manager installation or behavior, and is not a documentation error covered by this repository. For Tizen Studio tooling problems, please use the dedicated issue tracker below, where you can receive proper support:

- https://github.com/Samsung/Tizen.Issues

Since this is outside the scope of a documentation repository, we are closing the issue after providing the above pointer. Thank you for your understanding.
